name: Accessibility Testing

on:
  pull_request:
    branches: [ main, master ]

jobs:
  axe:
    name: Accessibility Testing
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build demo
      run: npm run build:demo
      
    - name: Start demo server
      run: |
        cd demo/dist
        npx serve -s . -l 3000 &
        sleep 10
      
    - name: Run accessibility tests
      run: |
        npm install -g axe-core
        npm install -g @axe-core/cli
        
        # Run axe-core tests
        axe http://localhost:3000 --exit --save results.json
        
        # Parse results and create report
        node -e "
          const fs = require('fs');
          const results = JSON.parse(fs.readFileSync('results.json', 'utf8'));
          
          let report = '## ♿ Accessibility Report\\n\\n';
          
          if (results.violations.length === 0) {
            report += '✅ No accessibility violations found!\\n\\n';
          } else {
            report += '❌ Accessibility violations found:\\n\\n';
            
            results.violations.forEach(violation => {
              report += \`### \${violation.impact.toUpperCase()}: \${violation.description}\\n\`;
              report += \`- **Rule**: \${violation.id}\\n\`;
              report += \`- **Help**: \${violation.help}\\n\`;
              report += \`- **Affected Elements**: \${violation.nodes.length}\\n\\n\`;
            });
          }
          
          fs.writeFileSync('accessibility-report.md', report);
        "
      
    - name: Comment PR
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const report = fs.readFileSync('accessibility-report.md', 'utf8');
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: report
          });
